/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RaceRouteImport } from './routes/race'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as QuizCreateRouteImport } from './routes/quiz.create'
import { Route as LessonsCreateRouteImport } from './routes/lessons.create'
import { Route as LearnSetIdRouteImport } from './routes/learn.$setId'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as LearnLessonLessonIdRouteImport } from './routes/learn.lesson.$lessonId'
import { Route as LearnCourseCourseIdRouteImport } from './routes/learn.course.$courseId'

const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCreateRoute = QuizCreateRouteImport.update({
  id: '/quiz/create',
  path: '/quiz/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsCreateRoute = LessonsCreateRouteImport.update({
  id: '/lessons/create',
  path: '/lessons/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSetIdRoute = LearnSetIdRouteImport.update({
  id: '/learn/$setId',
  path: '/learn/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonLessonIdRoute = LearnLessonLessonIdRouteImport.update({
  id: '/learn/lesson/$lessonId',
  path: '/learn/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseCourseIdRoute = LearnCourseCourseIdRouteImport.update({
  id: '/learn/course/$courseId',
  path: '/learn/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/race': typeof RaceRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/learn/$setId': typeof LearnSetIdRoute
  '/lessons/create': typeof LessonsCreateRoute
  '/quiz/create': typeof QuizCreateRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/race': typeof RaceRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/learn/$setId': typeof LearnSetIdRoute
  '/lessons/create': typeof LessonsCreateRoute
  '/quiz/create': typeof QuizCreateRoute
  '/learn': typeof LearnIndexRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/race': typeof RaceRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/learn/$setId': typeof LearnSetIdRoute
  '/lessons/create': typeof LessonsCreateRoute
  '/quiz/create': typeof QuizCreateRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/dashboard'
    | '/join'
    | '/launch'
    | '/login'
    | '/manual'
    | '/race'
    | '/register'
    | '/report'
    | '/settings'
    | '/standings'
    | '/folder/$folderId'
    | '/learn/$setId'
    | '/lessons/create'
    | '/quiz/create'
    | '/learn/'
    | '/learn/course/$courseId'
    | '/learn/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/dashboard'
    | '/join'
    | '/launch'
    | '/login'
    | '/manual'
    | '/race'
    | '/register'
    | '/report'
    | '/settings'
    | '/standings'
    | '/folder/$folderId'
    | '/learn/$setId'
    | '/lessons/create'
    | '/quiz/create'
    | '/learn'
    | '/learn/course/$courseId'
    | '/learn/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/dashboard'
    | '/join'
    | '/launch'
    | '/login'
    | '/manual'
    | '/race'
    | '/register'
    | '/report'
    | '/settings'
    | '/standings'
    | '/folder/$folderId'
    | '/learn/$setId'
    | '/lessons/create'
    | '/quiz/create'
    | '/learn/'
    | '/learn/course/$courseId'
    | '/learn/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  RaceRoute: typeof RaceRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  StandingsRoute: typeof StandingsRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
  LearnSetIdRoute: typeof LearnSetIdRoute
  LessonsCreateRoute: typeof LessonsCreateRoute
  QuizCreateRoute: typeof QuizCreateRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnCourseCourseIdRoute: typeof LearnCourseCourseIdRoute
  LearnLessonLessonIdRoute: typeof LearnLessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/create': {
      id: '/quiz/create'
      path: '/quiz/create'
      fullPath: '/quiz/create'
      preLoaderRoute: typeof QuizCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/create': {
      id: '/lessons/create'
      path: '/lessons/create'
      fullPath: '/lessons/create'
      preLoaderRoute: typeof LessonsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$setId': {
      id: '/learn/$setId'
      path: '/learn/$setId'
      fullPath: '/learn/$setId'
      preLoaderRoute: typeof LearnSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/lesson/$lessonId': {
      id: '/learn/lesson/$lessonId'
      path: '/learn/lesson/$lessonId'
      fullPath: '/learn/lesson/$lessonId'
      preLoaderRoute: typeof LearnLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/course/$courseId': {
      id: '/learn/course/$courseId'
      path: '/learn/course/$courseId'
      fullPath: '/learn/course/$courseId'
      preLoaderRoute: typeof LearnCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  RaceRoute: RaceRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  StandingsRoute: StandingsRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
  LearnSetIdRoute: LearnSetIdRoute,
  LessonsCreateRoute: LessonsCreateRoute,
  QuizCreateRoute: QuizCreateRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnCourseCourseIdRoute: LearnCourseCourseIdRoute,
  LearnLessonLessonIdRoute: LearnLessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
