/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RaceRouteImport } from './routes/race'
import { Route as PatronsRouteImport } from './routes/patrons'
import { Route as OrganisationRouteImport } from './routes/organisation'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CriteriaRouteImport } from './routes/criteria'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as CollabIndexRouteImport } from './routes/collab.index'
import { Route as QuizCreateRouteImport } from './routes/quiz.create'
import { Route as LessonsCreateRouteImport } from './routes/lessons.create'
import { Route as LearnSetIdRouteImport } from './routes/learn.$setId'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as CollabSettingsRouteImport } from './routes/collab.settings'
import { Route as CollabRequestsRouteImport } from './routes/collab.requests'
import { Route as CollabGroupsRouteImport } from './routes/collab.groups'
import { Route as CollabDirectRouteImport } from './routes/collab.direct'
import { Route as AdminCollabRouteImport } from './routes/admin.collab'
import { Route as LearnLessonLessonIdRouteImport } from './routes/learn.lesson.$lessonId'
import { Route as LearnCourseCourseIdRouteImport } from './routes/learn.course.$courseId'
import { Route as CollabGGroupIdRouteImport } from './routes/collab.g.$groupId'

const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronsRoute = PatronsRouteImport.update({
  id: '/patrons',
  path: '/patrons',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRoute = OrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriaRoute = CriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabIndexRoute = CollabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollabRoute,
} as any)
const QuizCreateRoute = QuizCreateRouteImport.update({
  id: '/quiz/create',
  path: '/quiz/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsCreateRoute = LessonsCreateRouteImport.update({
  id: '/lessons/create',
  path: '/lessons/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSetIdRoute = LearnSetIdRouteImport.update({
  id: '/learn/$setId',
  path: '/learn/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabSettingsRoute = CollabSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CollabRoute,
} as any)
const CollabRequestsRoute = CollabRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CollabRoute,
} as any)
const CollabGroupsRoute = CollabGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => CollabRoute,
} as any)
const CollabDirectRoute = CollabDirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => CollabRoute,
} as any)
const AdminCollabRoute = AdminCollabRouteImport.update({
  id: '/admin/collab',
  path: '/admin/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonLessonIdRoute = LearnLessonLessonIdRouteImport.update({
  id: '/learn/lesson/$lessonId',
  path: '/learn/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseCourseIdRoute = LearnCourseCourseIdRouteImport.update({
  id: '/learn/course/$courseId',
  path: '/learn/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabGGroupIdRoute = CollabGGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => CollabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/collab': typeof CollabRouteWithChildren
  '/criteria': typeof CriteriaRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/organisation': typeof OrganisationRoute
  '/patrons': typeof PatronsRoute
  '/race': typeof RaceRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/admin/collab': typeof AdminCollabRoute
  '/collab/direct': typeof CollabDirectRoute
  '/collab/groups': typeof CollabGroupsRoute
  '/collab/requests': typeof CollabRequestsRoute
  '/collab/settings': typeof CollabSettingsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/learn/$setId': typeof LearnSetIdRoute
  '/lessons/create': typeof LessonsCreateRoute
  '/quiz/create': typeof QuizCreateRoute
  '/collab/': typeof CollabIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/collab/g/$groupId': typeof CollabGGroupIdRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/criteria': typeof CriteriaRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/organisation': typeof OrganisationRoute
  '/patrons': typeof PatronsRoute
  '/race': typeof RaceRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/admin/collab': typeof AdminCollabRoute
  '/collab/direct': typeof CollabDirectRoute
  '/collab/groups': typeof CollabGroupsRoute
  '/collab/requests': typeof CollabRequestsRoute
  '/collab/settings': typeof CollabSettingsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/learn/$setId': typeof LearnSetIdRoute
  '/lessons/create': typeof LessonsCreateRoute
  '/quiz/create': typeof QuizCreateRoute
  '/collab': typeof CollabIndexRoute
  '/learn': typeof LearnIndexRoute
  '/collab/g/$groupId': typeof CollabGGroupIdRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/chat': typeof ChatRoute
  '/collab': typeof CollabRouteWithChildren
  '/criteria': typeof CriteriaRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/organisation': typeof OrganisationRoute
  '/patrons': typeof PatronsRoute
  '/race': typeof RaceRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/admin/collab': typeof AdminCollabRoute
  '/collab/direct': typeof CollabDirectRoute
  '/collab/groups': typeof CollabGroupsRoute
  '/collab/requests': typeof CollabRequestsRoute
  '/collab/settings': typeof CollabSettingsRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/learn/$setId': typeof LearnSetIdRoute
  '/lessons/create': typeof LessonsCreateRoute
  '/quiz/create': typeof QuizCreateRoute
  '/collab/': typeof CollabIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/collab/g/$groupId': typeof CollabGGroupIdRoute
  '/learn/course/$courseId': typeof LearnCourseCourseIdRoute
  '/learn/lesson/$lessonId': typeof LearnLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/chat'
    | '/collab'
    | '/criteria'
    | '/dashboard'
    | '/join'
    | '/launch'
    | '/login'
    | '/manual'
    | '/organisation'
    | '/patrons'
    | '/race'
    | '/register'
    | '/report'
    | '/results'
    | '/settings'
    | '/standings'
    | '/admin/collab'
    | '/collab/direct'
    | '/collab/groups'
    | '/collab/requests'
    | '/collab/settings'
    | '/folder/$folderId'
    | '/learn/$setId'
    | '/lessons/create'
    | '/quiz/create'
    | '/collab/'
    | '/learn/'
    | '/collab/g/$groupId'
    | '/learn/course/$courseId'
    | '/learn/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/chat'
    | '/criteria'
    | '/dashboard'
    | '/join'
    | '/launch'
    | '/login'
    | '/manual'
    | '/organisation'
    | '/patrons'
    | '/race'
    | '/register'
    | '/report'
    | '/results'
    | '/settings'
    | '/standings'
    | '/admin/collab'
    | '/collab/direct'
    | '/collab/groups'
    | '/collab/requests'
    | '/collab/settings'
    | '/folder/$folderId'
    | '/learn/$setId'
    | '/lessons/create'
    | '/quiz/create'
    | '/collab'
    | '/learn'
    | '/collab/g/$groupId'
    | '/learn/course/$courseId'
    | '/learn/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/chat'
    | '/collab'
    | '/criteria'
    | '/dashboard'
    | '/join'
    | '/launch'
    | '/login'
    | '/manual'
    | '/organisation'
    | '/patrons'
    | '/race'
    | '/register'
    | '/report'
    | '/results'
    | '/settings'
    | '/standings'
    | '/admin/collab'
    | '/collab/direct'
    | '/collab/groups'
    | '/collab/requests'
    | '/collab/settings'
    | '/folder/$folderId'
    | '/learn/$setId'
    | '/lessons/create'
    | '/quiz/create'
    | '/collab/'
    | '/learn/'
    | '/collab/g/$groupId'
    | '/learn/course/$courseId'
    | '/learn/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ChatRoute: typeof ChatRoute
  CollabRoute: typeof CollabRouteWithChildren
  CriteriaRoute: typeof CriteriaRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  OrganisationRoute: typeof OrganisationRoute
  PatronsRoute: typeof PatronsRoute
  RaceRoute: typeof RaceRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  StandingsRoute: typeof StandingsRoute
  AdminCollabRoute: typeof AdminCollabRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
  LearnSetIdRoute: typeof LearnSetIdRoute
  LessonsCreateRoute: typeof LessonsCreateRoute
  QuizCreateRoute: typeof QuizCreateRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnCourseCourseIdRoute: typeof LearnCourseCourseIdRoute
  LearnLessonLessonIdRoute: typeof LearnLessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrons': {
      id: '/patrons'
      path: '/patrons'
      fullPath: '/patrons'
      preLoaderRoute: typeof PatronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criteria': {
      id: '/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof CriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/': {
      id: '/collab/'
      path: '/'
      fullPath: '/collab/'
      preLoaderRoute: typeof CollabIndexRouteImport
      parentRoute: typeof CollabRoute
    }
    '/quiz/create': {
      id: '/quiz/create'
      path: '/quiz/create'
      fullPath: '/quiz/create'
      preLoaderRoute: typeof QuizCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/create': {
      id: '/lessons/create'
      path: '/lessons/create'
      fullPath: '/lessons/create'
      preLoaderRoute: typeof LessonsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$setId': {
      id: '/learn/$setId'
      path: '/learn/$setId'
      fullPath: '/learn/$setId'
      preLoaderRoute: typeof LearnSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/settings': {
      id: '/collab/settings'
      path: '/settings'
      fullPath: '/collab/settings'
      preLoaderRoute: typeof CollabSettingsRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/requests': {
      id: '/collab/requests'
      path: '/requests'
      fullPath: '/collab/requests'
      preLoaderRoute: typeof CollabRequestsRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/groups': {
      id: '/collab/groups'
      path: '/groups'
      fullPath: '/collab/groups'
      preLoaderRoute: typeof CollabGroupsRouteImport
      parentRoute: typeof CollabRoute
    }
    '/collab/direct': {
      id: '/collab/direct'
      path: '/direct'
      fullPath: '/collab/direct'
      preLoaderRoute: typeof CollabDirectRouteImport
      parentRoute: typeof CollabRoute
    }
    '/admin/collab': {
      id: '/admin/collab'
      path: '/admin/collab'
      fullPath: '/admin/collab'
      preLoaderRoute: typeof AdminCollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/lesson/$lessonId': {
      id: '/learn/lesson/$lessonId'
      path: '/learn/lesson/$lessonId'
      fullPath: '/learn/lesson/$lessonId'
      preLoaderRoute: typeof LearnLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/course/$courseId': {
      id: '/learn/course/$courseId'
      path: '/learn/course/$courseId'
      fullPath: '/learn/course/$courseId'
      preLoaderRoute: typeof LearnCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/g/$groupId': {
      id: '/collab/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/collab/g/$groupId'
      preLoaderRoute: typeof CollabGGroupIdRouteImport
      parentRoute: typeof CollabRoute
    }
  }
}

interface CollabRouteChildren {
  CollabDirectRoute: typeof CollabDirectRoute
  CollabGroupsRoute: typeof CollabGroupsRoute
  CollabRequestsRoute: typeof CollabRequestsRoute
  CollabSettingsRoute: typeof CollabSettingsRoute
  CollabIndexRoute: typeof CollabIndexRoute
  CollabGGroupIdRoute: typeof CollabGGroupIdRoute
}

const CollabRouteChildren: CollabRouteChildren = {
  CollabDirectRoute: CollabDirectRoute,
  CollabGroupsRoute: CollabGroupsRoute,
  CollabRequestsRoute: CollabRequestsRoute,
  CollabSettingsRoute: CollabSettingsRoute,
  CollabIndexRoute: CollabIndexRoute,
  CollabGGroupIdRoute: CollabGGroupIdRoute,
}

const CollabRouteWithChildren =
  CollabRoute._addFileChildren(CollabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ChatRoute: ChatRoute,
  CollabRoute: CollabRouteWithChildren,
  CriteriaRoute: CriteriaRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  OrganisationRoute: OrganisationRoute,
  PatronsRoute: PatronsRoute,
  RaceRoute: RaceRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  StandingsRoute: StandingsRoute,
  AdminCollabRoute: AdminCollabRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
  LearnSetIdRoute: LearnSetIdRoute,
  LessonsCreateRoute: LessonsCreateRoute,
  QuizCreateRoute: QuizCreateRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnCourseCourseIdRoute: LearnCourseCourseIdRoute,
  LearnLessonLessonIdRoute: LearnLessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
